# Generated by Django 2.0.10 on 2019-01-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlkeyword',
            name='down_count',
        ),
        migrations.RemoveField(
            model_name='urlkeyword',
            name='up_count',
        ),
    ]
